name: pro_net
description: "A new Flutter project."

publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^5.2.6
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.gif
    - assets/images/welcome.jpg
    - assets/images/welcome-nobg.png
    - assets/images/camera.png
    - assets/images/amd_logo.png
    - assets/images/intel_logo.png
