name: pro_net
description: "A new Flutter project."

publish_to: "none" # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Replace file_picker with file_selector and its platform-specific implementations
  file_selector: ^1.0.1
  file_selector_linux: ^0.9.2
  file_selector_macos: ^0.9.3+1
  file_selector_windows: ^0.9.3
  file_selector_android: ^0.5.0
  file_selector_ios: ^0.5.3+1

  # Add file_selector_web if you need web support
  # file_selector_web: ^0.9.1+1

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome.gif
    - assets/images/welcome.jpg
    - assets/images/welcome-nobg.png
    - assets/images/camera.png
    - assets/images/amd_logo.png
    - assets/images/intel_logo.png
